### ISSUE TITLE
can't configure

### ISSUE THREAD

**Issue by starrpark** [nillerusr/source-engine#278]
i type " `waf configure -T release --64bits` "

Error:
```
Checking for program 'git'
not found
find program=['git'] paths=['C:\\Program Files\\Common Files\\Oracle\\Java\\javapath', 'C:\\Program Files\\Eclipse Adoptium\\jre-8.0.372.7-hotspot\\bin', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'C:\\Program Files\\dotnet\\', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\', 'C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\1.0\\', 'C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\', 'C:\\Users\\290121_4\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\', 'C:\\Users\\290121_4\\AppData\\Local\\Programs\\Python\\Python311\\', 'C:\\Users\\290121_4\\AppData\\Local\\Microsoft\\WindowsApps', '', 'C:\\Users\\290121_4\\AppData\\Local\\Programs\\Microsoft VS Code\\bin'] var='GIT' -> None
from E:\SourceEngine: Could not find the program ['git']
-------------------------------------------------------
Checking for library libz
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Processing [32mbuild\conf_check_f3c5d811efc3b0352dd0e253c034df0f\test.cpp[0m

['E:\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\CL.exe', '/Fd:E:\\SourceEngine\\build\\conf_check_f3c5d811efc3b0352dd0e253c034df0f\\testbuild\\test.cpp.1.pdb', '/nologo', '/nologo', '/D_USING_V110_SDK71_', '/Zi', '/Zc:threadSafeInit-', '/O2', '/MT', '/IE:\\SourceEngine/thirdparty/SDL', '/arch:AVX', '/GF', '/Gy', '/fp:fast', '/Zc:forScope', '/Zc:wchar_t', '/GR', '/TP', '/EHsc', '/I..\\..\\..\\..\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\include', '/I..\\..\\..\\..\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\include', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\ucrt', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\shared', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\um', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\winrt', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\cppwinrt', '/I..\\..\\..\\common', '/DPLATFORM_64BITS=1', '/DWIN32=1', '/D_WIN32=1', '/D_WINDOWS', '/D_DLL_EXT=.dll', '/D_CRT_SECURE_NO_DEPRECATE', '/D_CRT_NONSTDC_NO_DEPRECATE', '/D_ALLOW_RUNTIME_LIBRARY_MISMATCH', '/D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH', '/D_ALLOW_MSC_VER_MISMATCH', '/DNO_X360_XDK', '/DNDEBUG', '/DGIT_COMMIT_HASH="[]"', '/DCOMPILER_MSVC=1', '/DMSVC=1', '/DCOMPILER_MSVC64=1', '..\\test.cpp', '/FC', '/c', '/FoE:\\SourceEngine\\build\\conf_check_f3c5d811efc3b0352dd0e253c034df0f\\testbuild\\test.cpp.1.o']
out: test.cpp


[2/2] Linking [33mbuild\conf_check_f3c5d811efc3b0352dd0e253c034df0f\testbuild\testprog.exe[0m

['E:\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\LINK.exe', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/DEBUG', '/INCREMENTAL', '/NODEFAULTLIB:libc', '/NODEFAULTLIB:libcd', '/NODEFAULTLIB:libcmtd', '/LARGEADDRESSAWARE', '/LIBPATH:E:\\SourceEngine/lib/win32/amd64/', '/LIBPATH:E:\\SourceEngine/dx9sdk/lib/amd64/', 'test.cpp.1.o', '/OUT:E:\\SourceEngine\\build\\conf_check_f3c5d811efc3b0352dd0e253c034df0f\\testbuild\\testprog.exe', '/LIBPATH:E:\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\lib\\x64', '/LIBPATH:E:\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.17763.0\\um\\x64', '/LIBPATH:E:\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\lib\\x64', '/LIBPATH:E:\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x64', '/LIBPATH:E:\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x86\\store\\references', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.17763.0', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.17763.0', '/LIBPATH:C:\\WINDOWS\\Microsoft.NET\\Framework64\\v4.0.30319', 'libz.lib']
out: LINK : fatal error LNK1104: íå óäàåòñÿ îòêðûòü ôàéë "libz.lib"


from C:\SourceEngine: Test does not build: Traceback (most recent call last):
  File "C:\SourceEngine\waf3-2.0.22-a21fa92a45548e4c642deabae50eb159\waflib\Configure.py", line 606, in run_build
    bld.compile()
  File "C:\SourceEngine\waf3-2.0.22-a21fa92a45548e4c642deabae50eb159\waflib\Build.py", line 359, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 1104 (run with -v to display more information)

not found
from E:\SourceEngine: The configuration failed
```

The full log
[config.log](https://github.com/nillerusr/source-engine/files/12136959/config.log)

help me

**Comment by TheKingFireS** [comment]
install ``git`` from your package manager.

**Comment by stephen-cusi** [comment]
[Git](https://git-scm.com/download/win) 
mam

**Comment by stephen-cusi** [comment]
[git](https://git-scm.com/download/win) 
Click on the link to download git
