### ISSUE TITLE
Portal builds on Darwin x86_64 but is broken and crashes easily

### ISSUE THREAD

**Issue by msikma** [nillerusr/source-engine#295]
Hi there. I just stumbled upon this project for the first time. It looks pretty impressive so I thought I'd give it a try.

I was able to build the engine, [using these instructions](https://jxhug.notion.site/Guide-to-Installing-Portal-Using-Source-Engine-on-macOS-660803f9ced149cfa1647d38fd5a7092), except that my build is in a separate directory rather than installed in the Steam folder.

My computer is an x86_64, and a Hackintosh at that, so I understand that what I'm doing might not be supported. But still I was hoping maybe someone had any thoughts on what's happening. For what it's worth, I've always had full compatibility with games.

The build seems to run at first, it loads the menu correctly. But then as soon as you load any test chamber it almost instantly crashes (after rendering a couple of glitched frames). The escape levels do load correctly and let you play for a while, but they eventually crash as well. Settings don't seem to matter.

Screenshots of the correctly working main menu, and of the glitched test chamber right before it crashes:

![Screenshot 2023-10-05 at 14 51 51](https://github.com/nillerusr/source-engine/assets/1507745/a4a26676-4ae9-4319-acee-ddd859b15e9e)

![vlcsnap-2023-10-05-00h25m37s400](https://github.com/nillerusr/source-engine/assets/1507745/8ac50763-bc89-4404-aa14-83bb83e6223f)

![vlcsnap-2023-10-05-00h33m19s865](https://github.com/nillerusr/source-engine/assets/1507745/f31e8ddd-a884-4e4e-84cf-4801764d1705)

Two videos I recorded of the escape levels, which work for a little while:

https://www.youtube.com/watch?v=8cK-OJzQEv0

https://www.youtube.com/watch?v=efqcOkgsXjY

Here's my logs:

* [Configure stage](https://gist.github.com/msikma/e493a8eea25a3175782e502ae9b1b5d0)
* [Build log](https://github.com/nillerusr/source-engine/files/12818595/2_build.txt.zip) (very large, so zipped)
* [Install](https://gist.githubusercontent.com/msikma/cfd465fc42ef997e954744036f607461/raw/a2819a8102e3a1ca9c93b6233f619c1b898ab082/3_install.txt)
* [Run](https://gist.githubusercontent.com/msikma/360660f3af253f7bab0f37de52e11f0c/raw/fa93ba1e065d049389ea216a3c37e6028e9f815a/4_run.txt)
* [engine.log](https://gist.githubusercontent.com/msikma/1670426ef94f1420f9b5289d5a42b4b0/raw/18f17276e63e869dd16e0e31d0b2579e49a706c1/engine.log.txt)
* [macOS crash log](https://gist.githubusercontent.com/msikma/b64c7c37b2df8d7c92d22b38074ea759/raw/05fd76f743e628a5405e474fcc2d6b3a41b3166a/osx%2520crash%2520log.txt)

Both a release build and a debug build doesn't work. I'm not entirely sure if there's a better way to get more debug info at this point.

Goes without saying, but Portal has always worked perfectly well on this computer back when I was on 10.14, and I generally never have any issues with games. I've never had any compatibility issues for any Source game or Mac games in general. It also works fine on my Windows install on the same machine. So I think it's probably a mistake with how I'm building the engine, rather than a fundamental issue with my setup.

Any help or thoughts would be appreciated!

**Comment by msikma** [comment]
Interestingly, I just did a little more testing. On my M1 Macbook, [Portal looks correct, but also crashes easily](https://www.youtube.com/watch?v=tZEDsqJ-Y_w).

On my Hackintosh I just installed Half-Life 2 and that one works perfectly, unlike Portal. So it seems there's definitely something unique about Portal causing it to be problematic.

**Comment by nillerusr** [comment]
Broken colors - that's known issue. #137 
Just disable color correction.

**Comment by nillerusr** [comment]
What about crash? Try to revert this commit locally - 8acf608b4d0fe0498f6037e1bfbdc1628254f656

**Comment by nillerusr** [comment]
```

Thread 1 "hl2_launcher" received signal SIGSEGV, Segmentation fault.
0x00007fffb3470b46 in TraceInfo_t::Visit (this=0x7fffb3c95960 <g_TraceInfo>, pBrush=0x7fff7c032a38, ndxBrush=897, cachedCount=1557868514, 
    pCachedCounters=0x0) at ../engine/cmodel_private.h:496
496             if ( *pCounter == cachedCount )
(gdb) bt
#0  0x00007fffb3470b46 in TraceInfo_t::Visit (this=0x7fffb3c95960 <g_TraceInfo>, pBrush=0x7fff7c032a38, ndxBrush=897, 
    cachedCount=1557868514, pCachedCounters=0x0) at ../engine/cmodel_private.h:496
#1  0x00007fffb3471440 in CM_TraceToLeaf<true> (pTraceInfo=0x7fffb3c95960 <g_TraceInfo>, ndxLeaf=165, startFrac=0, endFrac=1)
    at ../engine/cmodel.cpp:1475
#2  0x00007fffb346fbc6 in CM_RecursiveHullCheckImpl<true> (pTraceInfo=0x7fffb3c95960 <g_TraceInfo>, num=-166, p1f=0, p2f=1, p1=..., p2=...)
    at ../engine/cmodel.cpp:1970
#3  0x00007fffb346caf6 in CM_RecursiveHullCheck (pTraceInfo=0x7fffb3c95960 <g_TraceInfo>, num=0, p1f=0, p2f=1) at ../engine/cmodel.cpp:2018
#4  0x00007fffb346d885 in CM_BoxTrace (ray=..., headnode=0, brushmask=33570827, computeEndpt=true, tr=...) at ../engine/cmodel.cpp:2211
#5  0x00007fffb34d060d in CEngineTrace::TraceRay (this=0x7fffb3ca8200 <s_EngineTraceClient>, ray=..., fMask=33570827, 
    pTraceFilter=0x7ffffffeab20, pTrace=0x7ffffffeabf0) at ../engine/enginetrace.cpp:1704
#6  0x00007fff8b2feb66 in UTIL_TraceLine (vecAbsStart=..., vecAbsEnd=..., mask=33570827, ignore=0x0, collisionGroup=1, ptr=0x7ffffffeabf0)
    at ../game/shared/util_shared.h:255
#7  0x00007fff8b518158 in CParticleSystemQuery::TraceLine (this=0x7fff8be4a6e0 <s_ParticleSystemQuery>, vecAbsStart=..., vecAbsEnd=..., 
--Type <RET> for more, q to quit, c to continue without paging--c
    mask=33570827, ignore=0x0, collisionGroup=1, ptr=0x7ffffffeb560) at ../game/shared/particlesystemquery.cpp:147
#8  0x00007fff8b82cf69 in WorldIntersectT (pStartPnt=0x55555d5edb70, pEndPnt=0x7ffffffec940, nCollisionGroup=1, nMask=33570827, 
    pISectData=0x7ffffffeca90, pCtx=0x0) at ../particles/builtin_constraints.cpp:872
#9  0x00007fff8b832d8b in C_OP_WorldTraceConstraint::EnforceConstraintInternal<false, false> (this=0x5555582fb5a0, nStartBlock=0, 
    nNumBlocks=1, pParticles=0x55555d5eb9d0, pContext=0x55555afea090, nNumValidParticlesInLastChunk=4)
    at ../particles/builtin_constraints.cpp:1020
#10 0x00007fff8b82d208 in C_OP_WorldTraceConstraint::EnforceConstraint (this=0x5555582fb5a0, nStartBlock=0, nNumBlocks=1, 
    pParticles=0x55555d5eb9d0, pContext=0x55555afea090, nNumValidParticlesInLastChunk=4) at ../particles/builtin_constraints.cpp:908
#11 0x00007fff8b7daf3d in C_OP_BasicMovement::Operate (this=0x55555870afc0, pParticles=0x55555d5eb9d0, flStrength=1, pContext=0x55555afea000)
    at ../particles/builtin_particle_ops.cpp:222
#12 0x00007fff8b815a21 in CParticleCollection::Simulate (this=0x55555d5eb9d0, dt=0.00536830211, updateBboxOnly=false)
    at ../particles/particles.cpp:2073
#13 0x00007fff8b815aee in CParticleCollection::Simulate (this=0x55555d1a51e0, dt=0.00536830211, updateBboxOnly=false)
    at ../particles/particles.cpp:2103
#14 0x00007fff8b505273 in ProcessPSystem (pNewEffect=@0x55555c5eb0d0: 0x55555d1a51d0) at ../game/client/particlemgr.cpp:1571
#15 0x00007fff8b50cf62 in CFuncJobItemProcessor<CNewParticleEffect*>::Process (this=0x7fffffffbf60, item=@0x55555c5eb0d0: 0x55555d1a51d0)
    at ../public/vstdlib/jobthread.h:817
#16 0x00007fff8b50b016 in CParallelProcessor<CNewParticleEffect*, CFuncJobItemProcessor<CNewParticleEffect*> >::DoExecute (
    this=0x7fffffffbf60) at ../public/vstdlib/jobthread.h:936
#17 0x00007fff8b5098f0 in CParallelProcessor<CNewParticleEffect*, CFuncJobItemProcessor<CNewParticleEffect*> >::Run (this=0x7fffffffbf60, 
    pItems=0x55555c5eb0a0, nItems=8, nMaxParallel=2147483647, pThreadPool=0x7ffff7307de0 <g_ThreadPool>) at ../public/vstdlib/jobthread.h:904
#18 0x00007fff8b509670 in ParallelProcess<CNewParticleEffect*> (pszDescription=0x7fff8ba54978 "CParticleMgr::UpdateNewEffects", 
    pItems=0x55555c5eb0a0, nItems=8, pfnProcess=0x7fff8b50513c <ProcessPSystem(CNewParticleEffect*&)>, pfnBegin=0x0, pfnEnd=0x0, 
    nMaxParallel=2147483647) at ../public/vstdlib/jobthread.h:957
#19 0x00007fff8b506368 in CParticleMgr::UpdateNewEffects (this=0x7fff8bed4700 <ParticleMgr()::s_ParticleMgr>, flTimeDelta=0.00536830211)
    at ../game/client/particlemgr.cpp:1855
#20 0x00007fff8b506790 in CParticleMgr::UpdateAllEffects (this=0x7fff8bed4700 <ParticleMgr()::s_ParticleMgr>, flTimeDelta=0.00536830211)
    at ../game/client/particlemgr.cpp:1966
#21 0x00007fff8b504ebc in CParticleMgr::Simulate (this=0x7fff8bed4700 <ParticleMgr()::s_ParticleMgr>, flTimeDelta=0.00536830211)
    at ../game/client/particlemgr.cpp:1458
#22 0x00007fff8b3e928a in OnRenderStart () at ../game/client/cdll_client_int.cpp:2200
#23 0x00007fff8b3e9380 in CHLClient::FrameStageNotify (this=0x7fff8be8f4a0 <gHLClient>, curStage=FRAME_RENDER_START)
    at ../game/client/cdll_client_int.cpp:2250
#24 0x00007fffb35dc642 in ClientDLL_FrameStageNotify (frameStage=FRAME_RENDER_START) at ../engine/cdll_engine_int.cpp:2015
#25 0x00007fffb3683fc3 in SCR_UpdateScreen () at ../engine/gl_screen.cpp:261
#26 0x00007fffb34f09a5 in Host_UpdateScreen () at ../engine/host.cpp:2249
#27 0x00007fffb34f1a71 in _Host_RunFrame_Render () at ../engine/host.cpp:2786
#28 0x00007fffb34f2f15 in _Host_RunFrame (time=0.00536830211) at ../engine/host.cpp:3496
#29 0x00007fffb34f322f in Host_RunFrame (time=0.00536830211) at ../engine/host.cpp:3619
#30 0x00007fffb3505e0d in CHostState::State_Run (this=0x7fffb3cad780 <g_HostState>, frameTime=0.00536830211) at ../engine/host_state.cpp:505
#31 0x00007fffb35061c0 in CHostState::FrameUpdate (this=0x7fffb3cad780 <g_HostState>, time=0.00536830211) at ../engine/host_state.cpp:648
#32 0x00007fffb3505306 in HostState_Frame (time=0.00536830211) at ../engine/host_state.cpp:124
#33 0x00007fffb35a098f in CEngine::Frame (this=0x7fffb3cccd00 <g_Engine>) at ../engine/sys_engine.cpp:432
#34 0x00007fffb359b8a1 in CEngineAPI::MainLoop (this=0x7fffb3ccc900 <s_EngineAPI>) at ../engine/sys_dll2.cpp:1537
#35 0x00007fffb359c9a4 in CModAppSystemGroup::Main (this=0x7fffffffc470) at ../engine/sys_dll2.cpp:2109
#36 0x00007fffb38d9654 in CAppSystemGroup::Run (this=0x7fffffffc470) at ../appframework/AppSystemGroup.cpp:380
#37 0x00007fffb359c121 in CEngineAPI::RunListenServer (this=0x7fffb3ccc900 <s_EngineAPI>) at ../engine/sys_dll2.cpp:1818
#38 0x00007fffb359c2d7 in CEngineAPI::Run (this=0x7fffb3ccc900 <s_EngineAPI>) at ../engine/sys_dll2.cpp:1924
#39 0x00007ffff79c9865 in CSourceAppSystemGroup::Main (this=0x7fffffffc6c0) at ../launcher/launcher.cpp:851
#40 0x00007ffff79f432e in CAppSystemGroup::Run (this=0x7fffffffc6c0) at ../appframework/AppSystemGroup.cpp:380
#41 0x00007ffff79fd720 in CSteamApplication::Main (this=0x7fffffffc620) at ../appframework/posixapp.cpp:158
#42 0x00007ffff79f432e in CAppSystemGroup::Run (this=0x7fffffffc620) at ../appframework/AppSystemGroup.cpp:380
#43 0x00007ffff79ca90a in LauncherMain (argc=9, argv=0x7fffffffdc48) at ../launcher/launcher.cpp:1493
#44 0x0000555555555805 in main (argc=9, argv=0x7fffffffdc48) at ../launcher_main/main.cpp:297
```

Cool, that's not macos bug. I will fix it myself

**Comment by nillerusr** [comment]
Well, now all problems are solved

**Comment by msikma** [comment]
Thanks :)
Just wanted to confirm that it's working perfectly for me now, just rebuilt and tested it.
